language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_install:
  - composer self-update

install: composer update --prefer-source $COMPOSER_FLAGS

script: "phpunit -c phpunit.xml.dist"